version: '3.8'

services:
  asfalto-cafe-rota-preview:
    image: ghcr.io/aleduque75/asfalto-cafe-rota:latest
    container_name: asfalto-cafe-rota-preview
    restart: always
    ports:
      - "8085:3000"
    env_file:
      - .env
