/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRotasRouteImport } from './routes/_authenticated/rotas'
import { Route as AuthenticatedGaragemRouteImport } from './routes/_authenticated/garagem'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedGaragemIdRouteImport } from './routes/_authenticated/garagem.$id'
import { Route as AuthenticatedAdminNoticiasRouteImport } from './routes/_authenticated/admin/noticias'
import { Route as AuthenticatedAdminGaleriaRouteImport } from './routes/_authenticated/admin/galeria'
import { Route as AuthenticatedAdminConteudoRouteImport } from './routes/_authenticated/admin/conteudo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRotasRoute = AuthenticatedRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGaragemRoute = AuthenticatedGaragemRouteImport.update({
  id: '/garagem',
  path: '/garagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedGaragemIdRoute = AuthenticatedGaragemIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedGaragemRoute,
} as any)
const AuthenticatedAdminNoticiasRoute =
  AuthenticatedAdminNoticiasRouteImport.update({
    id: '/noticias',
    path: '/noticias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGaleriaRoute =
  AuthenticatedAdminGaleriaRouteImport.update({
    id: '/galeria',
    path: '/galeria',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConteudoRoute =
  AuthenticatedAdminConteudoRouteImport.update({
    id: '/conteudo',
    path: '/conteudo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/garagem': typeof AuthenticatedGaragemRouteWithChildren
  '/rotas': typeof AuthenticatedRotasRoute
  '/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/garagem/$id': typeof AuthenticatedGaragemIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/garagem': typeof AuthenticatedGaragemRouteWithChildren
  '/rotas': typeof AuthenticatedRotasRoute
  '/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/garagem/$id': typeof AuthenticatedGaragemIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/garagem': typeof AuthenticatedGaragemRouteWithChildren
  '/_authenticated/rotas': typeof AuthenticatedRotasRoute
  '/_authenticated/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/_authenticated/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/_authenticated/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/_authenticated/garagem/$id': typeof AuthenticatedGaragemIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/garagem'
    | '/rotas'
    | '/admin/conteudo'
    | '/admin/galeria'
    | '/admin/noticias'
    | '/garagem/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/garagem'
    | '/rotas'
    | '/admin/conteudo'
    | '/admin/galeria'
    | '/admin/noticias'
    | '/garagem/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/garagem'
    | '/_authenticated/rotas'
    | '/_authenticated/admin/conteudo'
    | '/_authenticated/admin/galeria'
    | '/_authenticated/admin/noticias'
    | '/_authenticated/garagem/$id'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rotas': {
      id: '/_authenticated/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AuthenticatedRotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garagem': {
      id: '/_authenticated/garagem'
      path: '/garagem'
      fullPath: '/garagem'
      preLoaderRoute: typeof AuthenticatedGaragemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/garagem/$id': {
      id: '/_authenticated/garagem/$id'
      path: '/$id'
      fullPath: '/garagem/$id'
      preLoaderRoute: typeof AuthenticatedGaragemIdRouteImport
      parentRoute: typeof AuthenticatedGaragemRoute
    }
    '/_authenticated/admin/noticias': {
      id: '/_authenticated/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/galeria': {
      id: '/_authenticated/admin/galeria'
      path: '/galeria'
      fullPath: '/admin/galeria'
      preLoaderRoute: typeof AuthenticatedAdminGaleriaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/conteudo': {
      id: '/_authenticated/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AuthenticatedAdminConteudoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminConteudoRoute: typeof AuthenticatedAdminConteudoRoute
  AuthenticatedAdminGaleriaRoute: typeof AuthenticatedAdminGaleriaRoute
  AuthenticatedAdminNoticiasRoute: typeof AuthenticatedAdminNoticiasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminConteudoRoute: AuthenticatedAdminConteudoRoute,
    AuthenticatedAdminGaleriaRoute: AuthenticatedAdminGaleriaRoute,
    AuthenticatedAdminNoticiasRoute: AuthenticatedAdminNoticiasRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedGaragemRouteChildren {
  AuthenticatedGaragemIdRoute: typeof AuthenticatedGaragemIdRoute
}

const AuthenticatedGaragemRouteChildren: AuthenticatedGaragemRouteChildren = {
  AuthenticatedGaragemIdRoute: AuthenticatedGaragemIdRoute,
}

const AuthenticatedGaragemRouteWithChildren =
  AuthenticatedGaragemRoute._addFileChildren(AuthenticatedGaragemRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGaragemRoute: typeof AuthenticatedGaragemRouteWithChildren
  AuthenticatedRotasRoute: typeof AuthenticatedRotasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGaragemRoute: AuthenticatedGaragemRouteWithChildren,
  AuthenticatedRotasRoute: AuthenticatedRotasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
